##  Neural Network

![title](figures/nural-network_3.gif)

To understand Neural Networks we will start with simple single Neuron.

![title](figures/SingleNeuron.jpg)

Let me give an example. It's not a very realistic example, but it's easy to understand,You want to attend meetup, and are trying to decide whether or not to go to the meetup.

Is it Regarding AI?
Is the Speaker is Famous?
Is that weekend?

We can represent these three factors by corresponding binary variables x1,x2, and x3. For instance, we'd have x1=1 if the MeetUp regarding AI, and x1=0 if the Meetup not Regarding AI. Similarly, x2=1 if Speaker is Famous, and x2=0 if not. And similarly again for x3 and is that Weekend.

I'll Take a person Name Venkatesh. I'll give his past 4 meetups Data. 

![title](figures/neural1.JPG)

Can you able to predict for Below Given Data?

![title](figures/neural2.JPG)

above Data have pattern. output values  are Strongly Relying on First Row .Let's try to solve using Simple Neuron Example

In [12]:
import numpy as np


In [13]:
# input dataset
X = np.array([  [0,0,1],
                [1,1,1],
                [1,0,1],
                [0,1,1] ])

print(X)

[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]


In [14]:
# output dataset            
y = np.array([[0,1,1,0]]).T
print(y)

[[0]
 [1]
 [1]
 [0]]


In [15]:
#Generating Random Weights
np.random.seed(4)
syn_w = 2 * np.random.random((3, 1)) - 1
print(syn_w)

[[0.93405968]
 [0.0944645 ]
 [0.94536872]]


In [16]:
# sigmoid function
def sigFunction(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [17]:
cy = sigFunction(np.dot(X,syn_w))
print("Before Training calculated output with Random Weights")
print(cy)

Before Training calculated output with Random Weights
[[0.72018284]
 [0.87802863]
 [0.86754546]
 [0.73881782]]


In [18]:


for iter in range(10000):

    cy = sigFunction(np.dot(X,syn_w))

    # how much did we miss?
    error = y - cy

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in cy
    l1_delta = error * sigFunction(cy,True)

    # update weights
    syn_w += np.dot(X.T,l1_delta)

print ("Output After Training:")
print (cy)
print ("Weights updated after Training")
print(syn_w)

Output After Training:
[[0.0096693 ]
 [0.99211692]
 [0.99359219]
 [0.0078624 ]]
Weights updated after Training
[[ 9.67299484]
 [-0.20868674]
 [-4.62913458]]


In [19]:
sigFunction(np.dot([[0,1,1]],syn_w))

array([[0.007862]])

In This Situation He is Not Going to Attend Meetup